#include <filesystem>
#include <iostream>
#include "SFML/Graphics.hpp"
#include "SFML/System.hpp"
#include "SFML/Window.hpp"
#include <SFML/Audio.hpp>
#include <sstream>
#include <regex>
#include <string>
#include <vector>
#include "Scene.h"
#include "Graphics.h"
#include "GameObject.h"
#include "Asteroid.h"
#include "SmallAsteroid.h"
#include "Projectile.h"
#include "EnemyProjectile.h"
#include "SpaceShip.h"
#include "EnemySpaceship.h"
#include "LoadingScene.h"
#include "MainMenuScene.h"
#include "HighScoreScene.h"
#include "PlayScene.h"
#include "Game.h"

